### ISSUE TITLE
Could not pass event HangingBreakByEntityEvent to HopperHopper 

### ISSUE THREAD

**Issue by fntsrlike** [david50407/HopperHopper#1]
修正 DB 在漏斗不存在時，仍嘗試清空資料庫的錯誤後，這邊又有新丟出的 Exception。

是這邊又沒有檢查就直接嘗試執行清空資料庫嗎？
https://github.com/david50407/HopperHopper/blob/master/src/main/java/tw/davy/minecraft/hopperhopper/listener/ItemFrameEventListener.java#L76

```
03:05:24 [ERROR] Could not pass event HangingBreakByEntityEvent to HopperHopper v1.0-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityHanging.damageEntity(EntityHanging.java:184) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityItemFrame.damageEntity(EntityItemFrame.java:50) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityHanging.t(EntityHanging.java:164) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:955) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1145) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at tw.davy.minecraft.hopperhopper.database.SqliteDatabase.clearFilter(SqliteDatabase.java:132) ~[?:?]
        at tw.davy.minecraft.hopperhopper.database.MetadataDatabase.clearFilter(MetadataDatabase.java:51) ~[?:?]
        at tw.davy.minecraft.hopperhopper.listener.ItemFrameEventListener.onItemFrameBreak(ItemFrameEventListener.java:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 20 more
```

**Comment by davy-tw** [comment]
fixed at https://github.com/david50407/HopperHopper/commit/060ad9e91bb1e3495f436a68fe51753d7bd40cdb
